/* 中文注释：统一错误码 */
export const ERRORS = {
  NAVIGATE_FAILED: 'NAVIGATE_FAILED',
  PAGE_NEW_FAILED: 'PAGE_NEW_FAILED',
  PAGE_LIST_FAILED: 'PAGE_LIST_FAILED',
  PAGE_CLOSE_FAILED: 'PAGE_CLOSE_FAILED',
  CLICK_FAILED: 'CLICK_FAILED',
  TYPE_FAILED: 'TYPE_FAILED',
  HOVER_FAILED: 'HOVER_FAILED',
  SCROLL_FAILED: 'SCROLL_FAILED',
  WAIT_FOR_FAILED: 'WAIT_FOR_FAILED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  EXTRACT_FAILED: 'EXTRACT_FAILED',
  EVALUATE_FAILED: 'EVALUATE_FAILED',
  SCREENSHOT_FAILED: 'SCREENSHOT_FAILED',
  WAIT_FOR_LOADSTATE_FAILED: 'WAIT_FOR_LOADSTATE_FAILED',
  WAIT_FOR_RESPONSE_FAILED: 'WAIT_FOR_RESPONSE_FAILED',
  COMMENT_FAILED: 'COMMENT_FAILED',
  COMMENT_TARGET_NOT_FOUND: 'COMMENT_TARGET_NOT_FOUND',
  FEED_TIMEOUT: 'FEED_TIMEOUT',
  MODAL_REQUIRED: 'MODAL_REQUIRED'
} as const

export type ErrorCode = keyof typeof ERRORS
